name: atomic-niri

description: Custom Fedora Atomic with Niri compositor

base-image: quay.io/fedora-ostree-desktops/base-atomic

image-version: 42 

modules:
  - from-file: common/lemurs-modules.yml
  - from-file: common/common-modules.yml
  - from-file: common/niri-modules.yml
  - from-file: common/final-modules.yml
