[customizations.installer.kickstart]
contents = "graphical reboot"

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Localization",
  "org.fedoraproject.Anaconda.Modules.Timezone"
]

