name: atomic-niri

description: Custom Fedora Atomic with Niri compositor

base-image: quay.io/fedora-ostree-desktops/base-atomic

image-version: 42 

modules:
  - from-file: lemurs-modules.yml
  - from-file: common-modules.yml
  - from-file: niri-modules.yml
  - from-file: final-modules.yml
