modules: 
    - type: rpm-ostree
      install:
        - git
        - cargo
        - rust
        - pam-devel
        - systemd-devel

    - type: script
      scripts:
        - build-lemurs.sh

    - type: systemd
      system:
        enabled:
          - lemurs.service
