name: Build and Push Atomic Image

on:
  schedule:
    - cron:
        "00 06 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - 'readme.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          tags: bootc
          containerfiles: ./containerfile

      - name: Push image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ steps.build-image.outputs.image }}
          tags: bootc

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign image with private key
        env:
          IMAGE: ghcr.io/${{ github.repository }}:bootc
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${IMAGE}"
