name: Build and Publish Atomic ISO

on:
  push:
    tags:
      - '[0-9]+[0-9]+*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'VERSION'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ISO
        id: build-iso
        uses: osbuild/bootc-image-builder-action@v0.0.2
        with:
          config-file: ./config.toml
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          types: |
            iso

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: atomic-niri-${{ env.VERSION }}.iso
          path: ${{ steps.build-iso.outputs.output-directory }}
          if-no-files-found: error
